import React, { useState, useEffect } from 'react';
import Hero from './components/Hero';
import Itinerary from './components/Itinerary';
import Loading from './components/Loading';
import { generateItinerary } from './services/geminiService';
import { TripItinerary } from './types';
import { Leaf } from 'lucide-react';

function App() {
  const [itinerary, setItinerary] = useState<TripItinerary | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Helper to parse city from URL
  const getCityFromUrl = () => {
    const params = new URLSearchParams(window.location.search);
    return params.get('city');
  };

  // Initial load: Check for city in URL
  useEffect(() => {
    const cityParam = getCityFromUrl();
    if (cityParam) {
      handleSearch(cityParam, false);
    }

    // Handle browser back/forward buttons
    const onPopState = () => {
      const city = getCityFromUrl();
      if (city) {
        handleSearch(city, false);
      } else {
        setItinerary(null);
      }
    };

    window.addEventListener('popstate', onPopState);
    return () => window.removeEventListener('popstate', onPopState);
  }, []);

  const handleSearch = async (city: string, shouldPushState = true) => {
    setLoading(true);
    setError(null);
    setItinerary(null);
    
    if (shouldPushState) {
      const newUrl = `${window.location.pathname}?city=${encodeURIComponent(city)}`;
      window.history.pushState({ path: newUrl }, '', newUrl);
    }
    
    try {
      const result = await generateItinerary(city);
      setItinerary(result);
    } catch (err) {
      setError("We couldn't generate an itinerary for that city. Please try again or choose a major city.");
    } finally {
      setLoading(false);
    }
  };

  const handleClear = () => {
    setItinerary(null);
    setError(null);
    // Clear URL when going back to home
    window.history.pushState({}, '', window.location.pathname);
  };

  return (
    <div className="min-h-screen font-sans text-gray-800">
      {/* Navigation Bar */}
      <nav className="p-6 flex justify-between items-center max-w-6xl mx-auto">
        <div className="flex items-center gap-2 cursor-pointer" onClick={handleClear}>
          <div className="bg-emerald-600 text-white p-1.5 rounded-lg">
            <Leaf className="w-6 h-6" />
          </div>
          <span className="text-xl font-bold text-emerald-900 tracking-tight">EcoTrek</span>
        </div>
        <div>
          <a href="#" className="text-sm font-medium text-emerald-800 hover:text-emerald-600 transition-colors">About Us</a>
        </div>
      </nav>

      <main className="px-4">
        {!itinerary && !loading && (
           <Hero onSearch={(city) => handleSearch(city, true)} isLoading={loading} />
        )}

        {loading && <Loading />}

        {error && (
          <div className="max-w-md mx-auto mt-10 p-6 bg-red-50 border border-red-100 rounded-2xl text-center text-red-800">
            <p>{error}</p>
            <button 
              onClick={() => setError(null)}
              className="mt-4 text-sm font-semibold underline hover:text-red-600"
            >
              Try Again
            </button>
          </div>
        )}

        {itinerary && !loading && (
          <div className="animate-fade-in-up">
            <div className="flex justify-end max-w-6xl mx-auto mb-4">
                <button 
                    onClick={handleClear}
                    className="text-sm text-emerald-600 hover:underline flex items-center gap-1"
                >
                    ← Start New Search
                </button>
            </div>
            <Itinerary data={itinerary} />
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="mt-20 py-10 bg-emerald-900 text-emerald-200/60 text-center text-sm">
        <div className="max-w-6xl mx-auto px-6">
            <p className="mb-2">&copy; {new Date().getFullYear()} EcoTrek. Generated by Gemini AI.</p>
            <p>Promoting sustainable travel one journey at a time.</p>
        </div>
      </footer>
    </div>
  );
}

export default App;